-- MySQL Script generated by MySQL Workbench
-- Mon Nov  1 11:46:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema texas_hamburger
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema texas_hamburger
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `texas_hamburger` DEFAULT CHARACTER SET utf8 ;
USE `texas_hamburger` ;

-- -----------------------------------------------------
-- Table `texas_hamburger`.`weekdays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `texas_hamburger`.`weekdays` (
  `value` INT NOT NULL,
  `day` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`value`),
  UNIQUE INDEX `value_UNIQUE` (`value` ASC) VISIBLE,
  UNIQUE INDEX `day_UNIQUE` (`day` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `texas_hamburger`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `texas_hamburger`.`branch` (
  `b_id` INT NOT NULL AUTO_INCREMENT,
  `b_title` VARCHAR(45) NOT NULL,
  `b_address` VARCHAR(45) NOT NULL,
  `b_city` VARCHAR(45) NOT NULL,
  `b_state` VARCHAR(45) NOT NULL,
  `b_city` VARCHAR(45) NOT NULL,
  `b_admin` VARCHAR(45) NOT NULL,
  `b_status` TINYINT NULL,
  `b_open` VARCHAR(45) NOT NULL,
  `b_close` VARCHAR(45) NOT NULL,
  `b_holiday` VARCHAR(45) NOT NULL,
  `weekdays_value` INT NOT NULL,
  PRIMARY KEY (`b_id`, `weekdays_value`),
  UNIQUE INDEX `b_id_UNIQUE` (`b_id` ASC) VISIBLE,
  UNIQUE INDEX `b_title_UNIQUE` (`b_title` ASC) VISIBLE,
  INDEX `fk_branch_weekdays1_idx` (`weekdays_value` ASC) VISIBLE,
  CONSTRAINT `fk_branch_weekdays1`
    FOREIGN KEY (`weekdays_value`)
    REFERENCES `texas_hamburger`.`weekdays` (`value`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `texas_hamburger`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `texas_hamburger`.`users` (
  `u_id` INT NOT NULL AUTO_INCREMENT,
  `u_firstname` VARCHAR(45) NOT NULL,
  `u_lastname` VARCHAR(45) NOT NULL,
  `u_role` VARCHAR(45) NOT NULL,
  `u_email` VARCHAR(45) NOT NULL,
  `u_mobile` VARCHAR(45) NOT NULL,
  `u_password` VARCHAR(45) NOT NULL,
  `u_address` VARCHAR(45) NULL,
  `u_city` VARCHAR(45) NULL,
  `u_state` VARCHAR(45) NULL,
  `u_zipcode` VARCHAR(45) NULL,
  `u_branch` INT NOT NULL,
  `u_status` TINYINT NULL,
  `branch_b_id` INT NOT NULL,
  PRIMARY KEY (`u_id`),
  UNIQUE INDEX `u_id_UNIQUE` (`u_id` ASC) VISIBLE,
  INDEX `fk_users_branch_idx` (`branch_b_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_branch`
    FOREIGN KEY (`branch_b_id`)
    REFERENCES `texas_hamburger`.`branch` (`b_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `texas_hamburger`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `texas_hamburger`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `branch` VARCHAR(45) NOT NULL,
  `users_u_id` INT NOT NULL,
  `branch_b_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_u_id`, `branch_b_id`),
  INDEX `fk_admin_users1_idx` (`users_u_id` ASC) VISIBLE,
  INDEX `fk_admin_branch1_idx` (`branch_b_id` ASC) VISIBLE,
  CONSTRAINT `fk_admin_users1`
    FOREIGN KEY (`users_u_id`)
    REFERENCES `texas_hamburger`.`users` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_branch1`
    FOREIGN KEY (`branch_b_id`)
    REFERENCES `texas_hamburger`.`branch` (`b_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
